### PR TITLE
Installation

### PR DESCRIPTION
**Pull request by pmav99**
This pull request adds a shell script that makes easier the installation in $GRASS_ADDONS. E.g.
``` bash
curl https://raw.githubusercontent.com/NikosAlexandris/i.fusion.hpf/master/install.sh | bash
```

### CODE REVIEW

**Comment by pmav99** [comment]
When you just want to download a single file, I don't think that there is any significant difference between them. For more advanced use cases, while `wget` has some unique features, I think that `curl` is stronger. E.g.
http://daniel.haxx.se/docs/curl-vs-wget.html
http://curl.haxx.se/docs/comparison-table.html

Nonetheless, both tools are easily installed. If you prefer `wget`, I can change it.

**Comment by pmav99** [comment]
With regard to the executable's name. Even though `python i.fusion.hpf.py` works fine when you are working interactively, is it equally easy to use when you want to write a GRASS script? I.e., is this going to work?
``` python
grass.script.run_command("i.fusion.hpf.py", **kwargs)
````
 (to be honest, I haven't tried it)

**Comment by NikosAlexandris** [comment]
No preferece really. In the shell script, curl is called 4 times. In any case, as far as I can understand GRASS, this is not a recommended way to do it. The right way is to push this in the grass-addons repository. I'd state a bold "use at your own risk" for the script. Is it ok for you to keep this in a different branch?

**Comment by pmav99** [comment]
> The right way is to push this in the grass-addons repository.
I don't disagree, but until this happens, there has to be an easy way to install the addon. Unfortunately the generic instructions did not work for me. I.e.
```
 make MODULE_TOPDIR=$GISBASE
```

> Thought that wget could get a directory, so less calls.
The number of calls is not really important. The network I/O is the decisive factor here. If you clone the whole repo or download the whole dir you are going to spend much more time. Of course, you can always download the "{branch_name/tag/whatever}.zip" but then you add additional dependencies (i.e. unzip). 

> Is it ok for you to keep this in a different branch?
Keeping this on a separate branch is fine with me. Actually, even if you don't want this on the repo is perfectly fine too. I can always maintain this on my `Dockerfile`s. I just thought that if I had trouble installing this, others might have too.

**Pull request closed without merging**
